version: '3.8'

services:
  # Ollama Service
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'  # Exponiert den Ollama-Server-Port
    volumes:
      - ollama_data:/root/.ollama  # Speichert Modell-Daten persistent
    networks:
      - app-network
    entrypoint: >
      /bin/sh -c "
        echo 'Starting Ollama server...' &&
        ollama start &
        echo 'Waiting for Ollama server to be ready...' &&
        sleep 15 &&
        echo 'Pulling embedding model mxbai-embed-large...' &&
        ollama pull mxbai-embed-large &&
        echo 'Model pulling complete.' &&
        wait"  # "wait" hält den Container offen

  # PostgreSQL mit pgvector
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=markets'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'  # PostgreSQL-Port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
